---
- hosts: all
  remote_user: root
  tasks:
    - name: install java
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
    - name: Download artifact 
      get_url:
        url: http://35.82.47.107:8082/artifactory/myartifactory/org/springframework/samples/spring-petclinic/LATEST/spring-petclinic-LATEST.jar
        dest: /tmp
        url_username: admin
        url_password: Dhana@123 
    - name: run java project
      shell: "java -jar /tmp/spring-petclinic-LATEST.jar"
      async: 10
      poll: 0

