---
- hosts: all
  remote_user: root
  tasks:
    - name: install java
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
    - name: Download artifact test
      get_url:
        url: http://52.37.61.194:8082/artifactory/myartifactory/org/springframework/samples/spring-petclinic/LATEST/spring-petclinic-LATEST.jar
        dest: /tmp
        url_username: admin
        url_password: Dhana@123 
    - name: run java project
      shell: java -jar /tmp/spring-petclinic-LATEST.jar
